name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    # - name: Build
    #   run: cargo build --bin rust-backend
    - name: Install psql
      run: sudo apt-get install -y postgresql-client
    - name: Check PSQL version
      run: psql --version
    - name: Export password
      run: export PGPASSWORD='password';
    - name: Run the migration
      run: psql postgres://test_user:testpassword@localhost:5434/test_db 
    #  run: psql -h localhost -d test_db -U test_user -p 5434 -W test_password -a -q -f ./bin/backend/setup.sql
    #- name: Test
    #  run: cargo test 
    #- name: Rust Code Coverage
    #  uses: Swatinem/fucov@v1.0.0
